# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Github:
    url: https://github.com/maartenderaedemaeker
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title:

# URL of the Home page image
index_cover: /images/theming/background.png

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: maarten-de-raedemaeker
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-97880416-1

# Addthis ID
addthis:

# set your own favicon
favicon: /images/theming/favicon.png

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/maartenderaedemaeker
gitlab_url:
linkedin_url: https://www.linkedin.com/in/maartenderaedemaeker/
mailto: